### ISSUE TITLE
[QUESTION] What's Your Purpose To Build That CSS Structure?

### ISSUE THREAD

**Issue by bgebes** [yunusemreerkesikbas/FrontendProjects#1]
### Hi Yunus Emre,

When I review style.css that created to project that [`dashboard`](https://github.com/yunusemreerkesikbas/FrontendProjects/tree/master/dashboard), I have been shocked. I'm seeing this structure first time. Can you describe this section? 

Section that I described: https://github.com/yunusemreerkesikbas/FrontendProjects/blob/master/dashboard/style.css#L3
<details>
  <summary>View as embed:</summary>
  <br />
  <code>html,
body,
div,
span,
applet,
object,
iframe,
h1,
h2,
h3,
h4,
h5,
h6,
p,
blockquote,
pre,
a,
abbr,
acronym,
address,
big,
cite,
code,
del,
dfn,
em,
img,
ins,
kbd,
q,
s,
samp,
small,
strike,
strong,
sub,
sup,
tt,
var,
b,
u,
i,
center,
dl,
dt,
dd,
ol,
ul,
li,
fieldset,
form,
label,
legend,
table,
caption,
tbody,
tfoot,
thead,
tr,
th,
td,
article,
aside,
canvas,
details,
embed,
figure,
figcaption,
footer,
header,
hgroup,
menu,
nav,
output,
ruby,
section,
summary,
time,
mark,
audio,
video {
    margin: 0;
    padding: 0;
    border: 0;
    font-size: 100%;
    font: inherit;
    vertical-align: baseline;
} </code>
</details>

- What's your purpose?
- Why did you choose that? 
- Why didn't you use `*` to target all tags(I guess)?
---
### Things that I can tell you as Adviser:

1. You can build a demo server and attach to repository url to show your projects. (You can use [Vercel](https://vercel.com/), [Netlify](https://www.netlify.com/), [Github Pages](https://pages.github.com/) or apps that like this)
2. You can split your projects to repositories. (Maybe you're doing that for basic practices, but you should create repository per project to use repository's props perfectly.)
3. You can fill [`README.md`](https://github.com/yunusemreerkesikbas/FrontendProjects/blob/master/README.md) to notify your watchers about project/projects. That should be confident and tidy. You can describe techs that used to that project.
4. You can move `font, img` folders into `assets` folder. When you review Open Source Code Folder Structure, you will see folders have been splitted to purposes. That can be another name for `assets`, but these are going to purpose same thing that store your images, logos, fonts, maybe [mock-data](https://stackoverflow.com/questions/2665812/what-is-mocking) and etc.
---
### Final

Firstly, this issue created to ask a question about your css structure and give some advice purposely education. If you don't want to receive issues that like this, just tell me via e-mail or comment to this issue. I don't want to disturb anyone. I'm following your projects and practices. You're going perfectly. I congratulate you. 👏

**Comment by yunusemreerkesikbas** [comment]
https://meyerweb.com/eric/tools/css/reset/  eric meyer'in reset.css tools'unu kullandım

**Comment by bgebes** [comment]
@yunusemreerkesikbas, teşekkürler!
